name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1.0.2
      with:
           activate-environment: teaching_microeconometrics
           environment-file: environment.yml
           python-version: 3.6
           auto-activate-base: false
    - name: run project
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        git submodule update --init --recursive
        run-project
        py.test
    - name: check notebook formatting
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        flake8-nb; [ $? -eq 0 ] || exit 1
        black-nb --check .; [ $? -eq 0 ] || exit 1
    - name: execute selected scripts
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        cd problem-sets/01-potential-outcome-model/data; python data-generation.py
        cd ../../03-regression-discontinuity-design/sources; python auxiliary.py
